name: adminer
services:
  adminer:
    image: adminer:4.8.1
    deploy:
      resources:
        reservations:
          memory: 32M
    restart: unless-stopped
    ports:
      - 8080:8085
    x-zettos:
      ports:
        - container: "8085"
          description:
            en_us: Adminer HTTP Port
            zh_cn: Adminer HTTP 端口
    container_name: adminer
x-zettos:
  architectures:
    - amd64
    - arm
    - arm64
  main: adminer
  author: Tim Düsterhus
  category: Utilities
  description:
    en_us: Adminer (formerly phpMinAdmin) is a full-featured database management tool written in PHP. Conversely to phpMyAdmin, it consist of a single file ready to deploy to the target server. Adminer is available for MySQL, PostgreSQL, SQLite, MS SQL, Oracle, Firebird, SimpleDB, Elasticsearch and MongoDB.
    zh_cn: Adminer（前身为phpMinAdmin）是一个用PHP编写的功能齐全的数据库管理工具。区别于phpMyAdmin，它仅为单个部署到目标服务器的文件（轻量）。Adminer可用于MySQL、PostgreSQL、SQLite、MS SQL、Oracle、Firebird、SimpleDB、Elasticsearch和MongoDB。
  developer: Jakub Vrána
  icon: Adminer/icon.webp
  screenshot_link:
    - Adminer/screenshot-1.webp
    - Adminer/screenshot-2.webp
    - Adminer/screenshot-3.webp
  tagline:
    en_us: Database management in a single PHP file
    zh_cn: 单PHP文件的数据库管理工具
  thumbnail: Adminer/thumbnail.webp
  title:
    en_us: Adminer
  port_map: '8085'

  required_memory: 32M
