name: swingmusic
services:
  swingmusic:
    image: ghcr.io/swingmx/swingmusic:v1.4.8
    container_name: swingmusic
    volumes:
      - type: bind
        source: /zettos/pool/1/virtual_machine/docker/DATA/installed/SwingMusic/config
        target: /config
      - type: bind
        source: /zettos/pool/1/virtual_machine/docker/DATA/installed/SwingMusic/media/Music
        target: /music
      - type: bind
        source: /zettos/raid/non-snapshot/fileservice/share
        target: /zettos_data
        bind:
          propagation: rshared
    ports:
      - "1970:1970"
    restart: unless-stopped
x-zettos:
  architectures:
    - amd64
  main: swingmusic
  author: ZettOS Team
  category: MultiMedia
  description:
    en_us: |
      Swing Music is a beautifully designed, self-hosted music streaming server. Like a cooler Spotify ... but bring your own music.
    zh_cn: |
      Swing Music 是一款设计精美的自托管音乐流媒体服务器。就像更酷的 Spotify......但可以带来你自己的音乐。
  developer: SwingMX
  icon: SwingMusic/icon.png
  screenshot_link:
  - SwingMusic/screenshot-1.png
  - SwingMusic/screenshot-2.png
  - SwingMusic/screenshot-3.png
  - SwingMusic/screenshot-4.png
  - SwingMusic/screenshot-5.png

  tagline:
    en_us: Swing Music is a beautifully designed, self-hosted music streaming server. Like a cooler Spotify ... but bring your own music.
    zh_cn: Swing Music 是一款设计精美的自托管音乐流媒体服务器。就像更酷的 Spotify......但可以带来你自己的音乐。
  tips:
    before_install:
      en_us: |
        When you first start Swing Music, it will ask you to pick music directory: Where do you want to look for music?
        select "Specific directories" Option, and select "/music" and rescan.
      zh_cn: |
        首次启动 Swing Music 时，它会要求您选择音乐目录：您想在哪里查找音乐？
        选择“特定目录”选项，然后选择“/music”并重新扫描。
  title:
    en_us: Swing Music
    zh_cn: Swing Music
  index: /
  port_map: "1970"
  scheme: http
  required_memory: 
