name: qbittorrent
services:
  qbittorrent:
    environment:
      WEBUI_PORT: 8181
      BT_PORT: 34567
      PGID: 1000
      PUID: 1000
      UMASK: "002"
      QB_USERNAME: ZettOS
      QB_PASSWORD: ZettOS
    image: nevinee/qbittorrent:5.0.3
    user: "1000:1000"
    deploy:
      resources:
        reservations:
          memory: "256M"
    network_mode: bridge
    ports:
      - target: 8181
        published: 8181
        protocol: tcp
      - target: 34567
        published: 34567
        protocol: tcp
      - target: 34567
        published: 34567
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /zettos/pool/1/virtual_machine/docker/DATA/installed/qBittorrent/data
        target: /data
      - type: bind
        source: /zettos/raid/non-snapshot/fileservice/share
        target: /zettos_data
        bind:
          propagation: rshared
    x-zettos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
            zh_cn: 时区
        - container: PUID
          description:
            en_us: Run qBittorrent as specified uid.
            zh_cn: 以指定的 uid 运行 qBittorrent。
        - container: PGID
          description:
            en_us: Run qBittorrent as specified gid.
            zh_cn: 以指定的 gid 运行 qBittorrent。
        - container: UMASK
          description:
            en_us: Run qBittorrent as specified UMASK.
            zh_cn: 以指定的 UMASK 运行 qBittorrent。
      ports:
        - container: "8080"
          description:
            en_us: WebUI HTTP Port
            zh_cn: WebUI HTTP 端口

      volumes:
        - container: /config
          description:
            en_us: qBittorrent config directory.
            zh_cn: qBittorrent 配置目录。
        - container: /DATA
          description:
            en_us: qBittorrent Accessible directory.
            zh_cn: qBittorrent 可访问目录。
    container_name: qbittorrent
x-zettos:
  architectures:
    - amd64
    - arm64
  main: qbittorrent
  author: ZettOS Team
  category: Downloader
  description:
    en_us: |
      **Elevate Your Home Media Experience**. qBittorrent transforms your home media setup with a polished interface reminiscent of µTorrent, minus the ads. Unlike traditional download tools, it offers a streamlined, efficient, and ad-free experience. This makes it a perfect fit for those seeking a hassle-free way to manage and enjoy their media collections at home.
      
      **Feature-Rich and User-Friendly**. With qBittorrent, you gain access to a well-integrated and extensible search engine, allowing simultaneous searches across multiple torrent sites, and category-specific searches for books, music, and software. Its support for RSS feeds with advanced filters, magnet links, encrypted connections, and more, ensures you have complete control over your downloads. Available on all major platforms and in around 70 languages, qBittorrent is both versatile and accessible.
      
      **Seamless Integration with Private Clouds like Zima**. Deploying qBittorrent on private cloud devices such as Zima offers unparalleled convenience. Enjoy virtually unlimited storage, enhanced privacy for your data, and local network speeds that make downloading and streaming effortless. This setup ensures that your media library is always at your fingertips, securely and swiftly.
    zh_cn: |
      **提升家庭媒体体验**。qBittorrent 通过一个类似于 µTorrent 的精美界面来改造您的家庭媒体设置，但没有广告。与传统下载工具不同，它提供了简洁、高效且无广告的体验，非常适合那些希望在家中轻松管理和享受媒体收藏的人。

      **功能丰富且用户友好**。使用 qBittorrent，您可以访问一个集成良好的可扩展搜索引擎，允许同时在多个种子站点进行搜索，并针对书籍、音乐和软件进行分类搜索。它支持带有高级过滤器的 RSS 提要、磁力链接、加密连接等功能，确保您完全控制下载过程。qBittorrent 在所有主要平台上可用，并支持约 70 种语言，既多功能又易于访问。

      **与 Zima 等私有云的无缝集成**。在像 Zima 这样的私有云设备上部署 qBittorrent，提供无与伦比的便利。享受几乎无限的存储空间、增强的数据隐私以及使下载和流媒体播放变得轻而易举的本地网络速度。这种设置确保您的媒体库始终触手可及，安全且快速。
    ar_sa: يهدف مشروع qBittorrent إلى توفير بديل مفتوح المصدر لـ µTorrent.
    de_de: Das qBittorrent-Projekt zielt darauf ab, eine Open-Source-Software-Alternative zu µTorrent zu bieten.
    es_es: El objetivo del proyecto qBittorrent es proporcionar una alternativa de software de código abierto a µTorrent.
    fr_fr: Le projet qBittorrent vise à fournir une alternative open source à µTorrent.
    hu_hu: A qBittorrent projekt célja, hogy nyílt forráskódú szoftver alternatívát nyújtson a µTorrent számára.
    it_it: Il progetto qBittorrent mira a fornire un'alternativa open source a µTorrent.
    ru_ru: Проект qBittorrent стремится предоставить альтернативу с открытым исходным кодом для µTorrent.
    pl_pl: Projekt qBittorrent ma na celu zapewnienie otwartoźródłowej alternatywy dla µTorrent.
    pt_br: O objetivo do projeto qBittorrent é fornecer uma alternativa de software de código aberto ao µTorrent.
    sv_se: qBittorrent-projektets mål är att erbjuda en öppen källkodsalternativ till µTorrent.
    uk_ua: Проект qBittorrent має на меті надати альтернативу з відкритим вихідним кодом для µTorrent.
  developer: qBittorrent
  icon: qBittorrent/icon.webp
  screenshot_link:
    - qBittorrent/screenshot-1.webp
    - qBittorrent/screenshot-2.webp
    - qBittorrent/screenshot-3.webp
  tagline:
    en_us: P2P bittorrent download
    zh_cn: P2P BT 下载
    ar_sa: مُنزِّل BitTorrent مجاني
    de_de: Kostenloser BitTorrent-Downloader
    es_es: Descargador de BitTorrent gratuito
    fr_fr: Téléchargeur BitTorrent gratuit
    hu_hu: Ingyenes BitTorrent letöltő
    it_it: Downloader BitTorrent gratuito
    ru_ru: Бесплатный загрузчик BitTorrent
    pl_pl: Darmowy downloader BitTorrent
    pt_br: Downloader BitTorrent gratuito
    sv_se: Gratis BitTorrent-downladdare
    uk_ua: Безкоштовний завантажувач BitTorrent
  thumbnail: qBittorrent/thumbnail.webp
  tips:
    default_account:
      username: ZettOS
      password: ZettOS
  title:
    en_us: qBittorrent
  index: /
  port_map: "8181"

  required_memory: 256M
