name: autobrr
services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:v1.57.0
    network_mode: bridge
    restart: unless-stopped
    environment:
      TZ: $TZ
    ports:
      - target: 7474
        published: "7474"
        protocol: tcp
    volumes:
      - type: bind
        source: /zettos/pool/1/virtual_machine/docker/DATA/installed/Autobrr
        target: /data
      - type: bind
        source: /zettos/raid/non-snapshot/fileservice/share
        target: /zettos_data
        bind:
          propagation: rshared
    x-zettos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
            zh_cn: 时区
      ports:
        - container: "7474"
          description:
            en_us: WebUI HTTP Port
            zh_cn: WebUI HTTP端口
      volumes:
        - container: /config
          description:
            en_us: Autobrr config directory
            zh_cn: Autobrr配置目录
x-zettos:
  main: autobrr
  required_memory: ""
  architectures:
    - amd64
    - arm
    - arm64
  port_map: "7474"
  title:
    en_us: Autobrr
  author: Autobrr Team
  developer: Autobrr Team
  category: MultiMedia
  icon: Autobrr/icon.webp
  thumbnail: Autobrr/thumbnail.webp
  screenshot_link:
    - Autobrr/screenshot-1.webp
    - Autobrr/screenshot-2.webp
  description:
    en_us: Autobrr is the modern download automation tool for torrents and usenet. With inspiration and ideas from tools like trackarr, autodl-irssi and flexget we built one tool that can do it all, and then some.
    zh_cn: Autobrr是用于torrents和Usenet的现代下载自动化工具。受到trackarr、autodl-irssi和flexget等工具的启发和理念，我们构建了一个可以完成所有这些任务的工具，甚至更多。
  tagline:
    en_us: Modern, easy to use download automation for torrents and usenet.
    zh_cn: 现代、易于使用的Torrents和Usenet下载自动化工具。
  index: /
  scheme: http

