name: jellyseerr
services:
  jellyseerr:
    cpu_shares: 50
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - LOG_LEVEL=debug
      - TZ=$TZ
    image: fallenbagel/jellyseerr:2.2.3
    ports:
      - mode: ingress
        target: 5055
        published: "5055"
        protocol: tcp
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - type: bind
        source: /zettos/pool/1/virtual_machine/docker/DATA/installed/Jellyseerr/media
        target: /media
      - type: bind
        source: /zettos/pool/1/virtual_machine/docker/DATA/installed/Jellyseerr/config
        target: /config
      - type: bind
        source: /zettos/raid/non-snapshot/fileservice/share
        target: /zettos_data
        bind:
          propagation: rshared
    network_mode: bridge
    privileged: false
x-zettos:
  scheme: http
  title:
    en_us: Jellyseerr
  architectures:
    - amd64
    - arm64
  main: jellyseerr
  author: Fallenbagel
  category: MultiMedia
  description:
    en_us: Jellyseerr is a free and open source software application for managing requests for your media library. It is a a fork of Overseerr built to bring support for Jellyfin & Emby media servers!
  developer: Fallenbagel
  icon: Jellyseerr/icon.webp
  screenshot_link:
    - Jellyseerr/screenshot-1.webp
    - Jellyseerr/screenshot-2.webp
    - Jellyseerr/screenshot-3.webp
  tagline:
    en_us: Jellyseerr is a free and open source software application for managing requests for your media library. It is a a fork of Overseerr built to bring support for Jellyfin & Emby media servers!
  thumbnail: Jellyseerr/thumbnail.webp
  tips: {}
  port_map: "5055"
